//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctusDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Tiempos
    {
        public int IdTiempo { get; set; }
        public int IdActividad { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Tiempo { get; set; }
    
        public virtual tbl_Actividades tbl_Actividades { get; set; }
    }
}
