//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctusDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Actividades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Actividades()
        {
            this.tbl_Tiempos = new HashSet<tbl_Tiempos>();
        }
    
        public int IdActividad { get; set; }
        public int IdUsuario { get; set; }
        public string Descripcion { get; set; }
    
        public virtual tbl_Usuarios tbl_Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Tiempos> tbl_Tiempos { get; set; }
    }
}
