//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctusDT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Data.Entity.ModelConfiguration.Conventions;

    public partial class Doctus_BDHorasEntities : DbContext
    {
        public Doctus_BDHorasEntities()
            : base("name=Doctus_BDHorasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Actividades> tbl_Actividades { get; set; }
        public virtual DbSet<tbl_Tiempos> tbl_Tiempos { get; set; }
        public virtual DbSet<tbl_Usuarios> tbl_Usuarios { get; set; }
    
        public virtual int sp_CrearActivades(Nullable<int> iN_IdUsuario, string iN_Descripcion)
        {
            var iN_IdUsuarioParameter = iN_IdUsuario.HasValue ?
                new ObjectParameter("IN_IdUsuario", iN_IdUsuario) :
                new ObjectParameter("IN_IdUsuario", typeof(int));
    
            var iN_DescripcionParameter = iN_Descripcion != null ?
                new ObjectParameter("IN_Descripcion", iN_Descripcion) :
                new ObjectParameter("IN_Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CrearActivades", iN_IdUsuarioParameter, iN_DescripcionParameter);
        }
    
        public virtual int sp_CrearTiempos(Nullable<int> iN_IdActividad, string iN_Fecha, Nullable<int> iN_Tiempo)
        {
            var iN_IdActividadParameter = iN_IdActividad.HasValue ?
                new ObjectParameter("IN_IdActividad", iN_IdActividad) :
                new ObjectParameter("IN_IdActividad", typeof(int));
    
            var iN_FechaParameter = iN_Fecha != null ?
                new ObjectParameter("IN_Fecha", iN_Fecha) :
                new ObjectParameter("IN_Fecha", typeof(string));
    
            var iN_TiempoParameter = iN_Tiempo.HasValue ?
                new ObjectParameter("IN_Tiempo", iN_Tiempo) :
                new ObjectParameter("IN_Tiempo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CrearTiempos", iN_IdActividadParameter, iN_FechaParameter, iN_TiempoParameter);
        }
    
        public virtual int sp_EliminarActividad(Nullable<int> iN_IdActividad)
        {
            var iN_IdActividadParameter = iN_IdActividad.HasValue ?
                new ObjectParameter("IN_IdActividad", iN_IdActividad) :
                new ObjectParameter("IN_IdActividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarActividad", iN_IdActividadParameter);
        }
    
        public virtual int sp_EliminarTiempo(Nullable<int> iN_IdTiempo)
        {
            var iN_IdTiempoParameter = iN_IdTiempo.HasValue ?
                new ObjectParameter("IN_IdTiempo", iN_IdTiempo) :
                new ObjectParameter("IN_IdTiempo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarTiempo", iN_IdTiempoParameter);
        }
    
        public virtual ObjectResult<sp_ListarActivades_Result> sp_ListarActivades(Nullable<int> iN_IdUsuario)
        {
            var iN_IdUsuarioParameter = iN_IdUsuario.HasValue ?
                new ObjectParameter("IN_IdUsuario", iN_IdUsuario) :
                new ObjectParameter("IN_IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarActivades_Result>("sp_ListarActivades", iN_IdUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_ListarTiempos_Result> sp_ListarTiempos(Nullable<int> iN_IdActividad)
        {
            var iN_IdActividadParameter = iN_IdActividad.HasValue ?
                new ObjectParameter("IN_IdActividad", iN_IdActividad) :
                new ObjectParameter("IN_IdActividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarTiempos_Result>("sp_ListarTiempos", iN_IdActividadParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_ValidarUsuario(string iN_Usuario, string iN_Clave)
        {
            var iN_UsuarioParameter = iN_Usuario != null ?
                new ObjectParameter("IN_Usuario", iN_Usuario) :
                new ObjectParameter("IN_Usuario", typeof(string));
    
            var iN_ClaveParameter = iN_Clave != null ?
                new ObjectParameter("IN_Clave", iN_Clave) :
                new ObjectParameter("IN_Clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ValidarUsuario", iN_UsuarioParameter, iN_ClaveParameter);
        }
    }
}
